import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { NgForm } from '@angular/forms';

@Component({
  selector: 'app-input-button-unit',
  template:`
  <form #itemForm="ngForm" (ngSubmit)="submitValue(itemForm)">
  <div class="form-group">
  <input class="todo-input form-control" 
        required
        name="title"
        [(ngModel)]="title">
  </div>
  <button class="btn">
  Save
  </button>
  </form>
  `,
  styleUrls: ['./input-button-unit.component.scss']
})
export class InputButtonUnitComponent implements OnInit {

  @Output() submitItem: EventEmitter<string> = new EventEmitter();

  title = 'My first input button';
  
  constructor() {
  }

  ngOnInit() {

  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  submitValue(newTitleForm: NgForm) {
    if(newTitleForm.valid) {
      this.submitItem.emit(newTitleForm.value.title);
    } else {
      alert('your form is invalid');
    }    
    console.log(newTitleForm.value.title);
    // this.title = newTitle;
    // console.log(this.title);
  }

}
