import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  template: `
    <p>
      input-button-unit works!
      The title is: {{ title }}
    </p>

    <input [value]="title"
       (keyup.enter)="changeTitle($event.target.value)">
    <button (click)="changeTitle('Button Clicked!')">
      Save
    </button>
  `,
  styleUrls: ['./input-button-unit.component.scss']
})
export class InputButtonUnitComponent implements OnInit {
  title = 'My first input button';
  constructor() {
  }

  ngOnInit() {
    
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  changeTitle(newTitle: string) {
    // console.log(newTitle);
    this.title = newTitle;
    // console.log(this.title);
  }

}
